### ISSUE TITLE
Some results from requests session not of type Response?

### ISSUE THREAD

**Issue by dcloud** [sunlightlabs/thezombies#18]
Running the data catalog validation for Interior triggers an error when attempting to transform a requests response to a dict. For some reason we are getting back an object that isn't a request.

```
[2015-01-21 17:43:41,659: ERROR/MainProcess] Task thezombies.tasks.main.audit_for_agency_url[25d5d8f7-e091-466b-8df0-13262bef1e98] raised unexpected: TypeError('resp is not an instance of a requests.Response',)
Traceback (most recent call last):
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "thezombies/tasks/main.py", line 93, in audit_for_agency_url
    result = request_url((url))
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "thezombies/tasks/urls.py", line 91, in request_url
    returnval['response'] = response_to_dict(resp)
  File "thezombies/tasks/utils.py", line 61, in response_to_dict
    raise TypeError('resp is not an instance of a requests.Response')
TypeError: resp is not an instance of a requests.Response
```

**Comment by dcloud** [comment]
60cbb25 and 793a3f4 should fix this and a history recursion error I introduced.
