### ISSUE TITLE
Parsing large json and inserting into db can cause error 

### ISSUE THREAD

**Issue by dcloud** [sunlightlabs/thezombies#19]
```
2015-01-22 12:15:46,122: ERROR/MainProcess] Task thezombies.tasks.main.parse_json_from_inspection[e84e17fa-a931-4a03-b079-480f9f820330] raised unexpected: MemoryError()
Traceback (most recent call last):
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "thezombies/tasks/main.py", line 52, in parse_json_from_inspection
    probe.save()
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _save_table
    forced_update)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/base.py", line 723, in _do_update
    return filtered._update(values) > 0
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/query.py", line 600, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/projects/thezombies/virt/local/lib/python2.7/site-packages/psycopg2/extras.py", line 649, in _getquoted_9
    return b("hstore(") + k.getquoted() + b(", ") + v.getquoted() + b(")")
MemoryError
```

**Comment by dcloud** [comment]
Need to retry while monitoring the db server memory.

**Comment by dcloud** [comment]
Looks like #16 is related.

**Comment by dcloud** [comment]
145M json files. Need streaming or server specs as beefy as my laptop. Heh.

**Comment by dcloud** [comment]
Now streaming json so we don't have to store large objects, just small ones.
